### ISSUE TITLE
Punctuation in merged fields

### ISSUE THREAD

**Issue by ammsalme** [NatLibFi/melinda-merge#147]
Punctuation should be fixed when fields are merged:

```
700 1  ‡aMöller, Johanna,‡etaiteilija.
700 1  ‡aMöller, Johanna.
```
Currently merges as:
`700 1  ‡aMöller, Johanna.‡etaiteilija.
`

Should merge as:
`700 1  ‡aMöller, Johanna,‡etaiteilija.`

**Comment by ammsalme** [comment]
See:
Older perl-version of agent entry punctuation: https://github.com/NatLibFi/MARC-Record-AutoPunct
Caretaker has implementation of punctutation: https://github.com/NatLibFi/aleph-record-caretaker/
There is also version used in replication.

**Comment by natlibfi-arlehiko** [comment]
Depends on natlibfi/marc-record-punctuation#1
